---
- name: "DEBIAN | Installing ufw package"
  ansible.builtin.package:
    name: ufw
    state: present
  when: ansible_os_family == "Debian"

- name: "Redhat | Tasks for Redhat family"
  when: ansible_os_family in ["RedHat", "Rocky", "OracleLinux" ]
  block:
    - name: "REDHAT | Import EPEL GPG key."
      ansible.builtin.rpm_key:
        key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
        state: present

    - name: "REDHAT | Installing epel-release"
      ansible.builtin.yum:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present

    - name: "REDHAT | Installing ufw package"
      ansible.builtin.yum:
        name: ufw
        state: present

- name: "Start and enable ufw"
  community.general.ufw:
    state: enabled

- name: "Configuring service"
  ansible.builtin.template:
    src: "ufw.j2"
    dest: "{{ ufw_config_file }}"
    mode: 0644
  notify: reload ufw
  when: ufw_manage_config

- name: "Applying rules"
  community.general.ufw:
    comment: "{{ item.comment | default(omit) }}"
    default: "{{ item.default | default(omit) }}"
    delete: "{{ item.delete | default(omit) }}"
    direction: "{{ item.direction | default(omit) }}"
    from_ip: "{{ item.from_ip | default(omit) }}"
    from_port: "{{ item.from_port | default(omit) }}"
    insert: "{{ item.insert | default(omit) }}"
    insert_relative_to: "{{ item.insert_relative_to | default(omit) }}"
    interface: "{{ item.interface | default(omit) }}"
    interface_in: "{{ item.interface_in | default(omit) }}"
    interface_out: "{{ item.interface_out | default(omit) }}"
    log: "{{ item.log | default(omit) }}"
    logging: "{{ item.logging | default(omit) }}"
    name: "{{ item.name | default(omit) }}"
    proto: "{{ item.proto | default(omit) }}"
    route: "{{ item.route | default(omit) }}"
    rule: "{{ item.rule | default(omit) }}"
    to_ip: "{{ item.to_ip | default(omit) }}"
    to_port: "{{ item.to_port | default(omit) }}"
  with_items: "{{ ufw_rules }}"

- name: "Add Docker specific after rules"
  ansible.builtin.copy:
    src: 'after.rules'
    dest: '/etc/ufw/after.rules'
    mode: '0640'
  when: ufw_docker
