---
- name: Run role
  hosts: all
  become: true
  any_errors_fatal: true

  roles:
    - role: ansible-apps_ufw
  vars:
    ufw_manage_config: true
    ufw_docker: false
    ufw_config:
      IPV6: "no"
      DEFAULT_INPUT_POLICY: DROP
      DEFAULT_OUTPUT_POLICY: ACCEPT
      DEFAULT_FORWARD_POLICY: DROP
      DEFAULT_APPLICATION_POLICY: SKIP
      MANAGE_BUILTINS: "no"
      IPT_SYSCTL: /etc/ufw/sysctl.conf
      IPT_MODULES:
